# Generated by Django 5.0.6 on 2024-06-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApi', '0002_remove_cart_name_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
