# Generated by Django 5.0.6 on 2024-06-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApi', '0004_alter_cart_id_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
