# Generated by Django 5.0.6 on 2024-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverApi', '0005_alter_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://img.freepik.com/free-vector/shopping-cart-realistic_1284-6011.jpg?size=338&ext=jpg&ga=GA1.1.1141335507.1718064000&semt=ais_user', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.ManyToManyField(related_name='products', to='serverApi.product'),
        ),
    ]
